---
author: "hvturingga"
name: "github.com/hvxahv/hvx"
version: "0.1.0	"
github: "https://github.com/hvxahv"

# Set instance domain.
domain: "h.disism.com"

authentication:
  admin:
    user: ""
    key: ""
  token:
    secret: "jwt_key_hvxahv.half_memories.com"
    # expiration time, days.
    expired: "60"

ipfs:
  address: "http://127.0.0.1:5001/api/v0"
  gateway: "http://127.0.0.1:8081/ipfs/"

matrix:
  address: "https://matrix.disism.com"

cockroach:
  host: "127.0.0.1"
  port: "26257"
  user: "root"
  password: "root"
  database: "hvxahv"
  ssl: "disable"
  timezone: "Asia/Shanghai"

redis:
  addr: "127.0.0.1:6379"
  password: "hvxahv123"

fs:
  minio:
    endpoint: "127.0.0.1:9000"
    accessKeyID: "hvxahv"
    secretAccessKey: "hvxahv123"
    useSSL: false
    region: "ap-northeast-3"

nats:
  address: ""

discovery:
  consul:
    address: "127.0.0.1:8500"
  etcd:
    address: ""

bot:
  telegram:
    id: ""
    token: ""

microsvcs:
  gateway:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "8080"
      grpc: "50000"

  account:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7010"
      grpc: "50010"

  actor:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7020"
      grpc: "50020"

  auth:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7030"
      grpc: "50030"

  public:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7040"
      grpc: "50040"

  device:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7050"
      grpc: "50050"

  channel:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7060"
      grpc: "50060"

  article:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7070"
      grpc: "50070"

  saved:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7080"
      grpc: "50080"

  activity:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7090"
      grpc: "50090"

  fs:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7100"
      grpc: "60100"

  message:
    version: "0.1.0"
    hostname: "127.0.0.1"
    useSSL: false
    ports:
      http: "7110"
      grpc: "60110"
