---
version: "3.3"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/etc/redis/redis.conf"
    command: redis-gateway /etc/redis/redis.conf
    ports:
      - 6379:6379

  nats:
    image: nats
    container_name: nats
    restart: always
    command: "-m 8222"
    ports:
      - 4222:4222
      - 8222:8222

  mariadb:
    image: mariadb
    container_name: maria
    restart: always
    volumes:
      - "./maria/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: hvxahv123
    ports:
      - 3306:3306

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - "./mongo/:/data/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hvxahv123
    ports:
      - 27017:27017

  postgres:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: hvxahv123
      POSTGRES_DB: kuma
    ports:
      - 5432:5432