---
activitypub: ""

port:
  accounts: "8088"
  status: "8005"
  articles: "8010"
  bot: "9000"
  gateway: "7000"
  inbox: "7050"
  outbox: "7080"

mariadb:
  hostname: ""
  prot: ""
  username: ""
  password: ""
  dbname: ""

mongo:
  address: ""
  username: ""
  password: ""
  name: ""


redis:
  address: ""
  password: ""
