---
activitypub: ""

port:
  accounts: ""
  status: ""
  articles: ""
  bot: ""
  gateway: ""

mariadb:
  hostname: ""
  prot: ""
  username: ""
  password: ""
  dbname: ""

mongo:
  address: ""
  username: ""
  password: ""
  name: ""


redis:
  address: ""
  password: ""
